# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: helmut 
      url-base: https://github.com/hlord2000

  projects:
    - name: nrf
      remote: helmut 
      repo-path: sdk-nrf
      revision: main
      import: true
